# List of NES games
nes_games = [
    "Adventure Island II (USA).nes",
    "Adventures of Lolo (USA).nes",
    "Adventures of Rad Gravity, The (USA).nes",
    "Aladdin (Unl).nes",
    "Bad Dudes (USA).nes",
    "Balloon Fight (USA).nes",
    "Batman - The Video Game (USA).nes",
    "Battle of Olympus, The (USA).nes",
    "BattleCity (Japan).nes",
    "Battletoads (USA).nes",
    "Battletoads-Double Dragon (USA).nes",
    "Binary Land (Japan).nes",
    "Bionic Commando (USA).nes",
    "Blades of Steel (USA).nes",
    "Bomberman II (USA).nes",
    "Bubble Bobble (USA).nes",
    "Bucky O'Hare (USA).nes",
    "BurgerTime (USA).nes",
    "Cabal (USA).nes",
    "Captain Skyhawk (USA) (Rev 1).nes",
    "Captain Tsubasa II - Super Striker (Japan).nes",
    "Celeste Mario's Zap & Dash (Unl).nes",
    "Chip 'n Dale - Rescue Rangers (USA).nes",
    "Chou-Wakusei Senki - MetaFight (Japan).nes",
    "Circus Charlie (Japan).nes",
    "Clash at Demonhead (USA).nes",
    "Commando (USA).nes",
    "Contra (Japan).nes",
    "Contra Force (USA).nes",
    "Crash 'n' the Boys - Street Challenge (USA).nes",
    "Crisis Force (Japan).nes",
    "Crystalis (USA).nes",
    "Darkwing Duck (USA).nes",
    "Deadpool (Unl).nes",
    "Die Hard (USA).nes",
    "Dig Dug (Japan).nes",
    "Donkey Kong (World) (Rev 1).nes",
    "Donkey Kong Jr. (World) (Rev 1).nes",
    "Double Dragon (USA).nes",
    "Double Dragon II - The Revenge (USA) (Rev 1).nes",
    "Double Dribble (USA) (Rev 1).nes",
    "Downtown - Nekketsu Koushinkyoku - Soreyuke Daiundoukai (Japan).nes",
    "Downtown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou (Japan).nes",
    "Dr. Mario (Japan, USA) (En) (Rev 1).nes",
    "Dragon Spirit - The New Legend (USA).nes",
    "Duck Hunt (World).nes",
    "DuckTales (USA).nes",
    "Elevator Action (USA).nes",
    "Faxanadu (USA) (Rev 1).nes",
    "Felix the Cat (USA).nes",
    "Fire 'n Ice (USA).nes",
    "Flintstones, The - The Rescue of Dino & Hoppy (USA).nes",
    "G.I. Joe - A Real American Hero (USA).nes",
    "Gargoyle's Quest II (USA).nes",
    "Ghosts'n Goblins (USA).nes",
    "Gimmick (Japan).nes",
    "Goonies (Japan).nes",
    "Guardian Legend, The (USA).nes",
    "Guerrilla War (USA).nes",
    "Gun Nac (USA).nes",
    "Gun.Smoke (USA).nes",
    "Hebereke (Japan).nes",
    "Hogan's Alley (World).nes",
    "Ice Climber (USA, Europe, Korea) (En).nes",
    "Ice Hockey (USA).nes",
    "Ike Ike Nekketsu Hockey-bu - Subette Koronde Dairantou (Japan).nes",
    "Jackal (USA).nes",
    "Journey to Silius (USA).nes",
    "KickMaster (USA).nes",
    "Kid Icarus (USA, Europe) (Rev 1).nes",
    "Kirby's Adventure (USA) (Rev 1).nes",
    "Kung Fu (Japan, USA) (En).nes",
    "Kunio-kun no Nekketsu Soccer League (Japan).nes",
    "Legend of Kage, The (USA).nes",
    "Legend of Zelda, The (USA) (Rev 1).nes",
    "Lemmings (USA).nes",
    "Life Force (USA) (Rev 1).nes",
    "Little Mermaid, The (USA).nes",
    "Little Nemo - The Dream Master (USA).nes",
    "Little Samson (USA).nes",
    "Lode Runner (USA).nes",
    "Mad City (Japan).nes",
    "Magic of Scheherazade, The (USA).nes",
    "Maniac Mansion (USA).nes",
    "Mappy (Japan).nes",
    "Marble Madness (USA).nes",
    "Mario Bros. (World).nes",
    "Mega Man (USA).nes",
    "Mega Man 2 (USA).nes",
    "Mega Man 3 (USA).nes",
    "Mega Man 4 (USA) (Rev 1).nes",
    "Mega Man 5 (USA).nes",
    "Mega Man 6 (USA).nes",
    "Metal Gear (USA).nes",
    "Metal Storm (USA).nes",
    "Metroid (USA).nes",
    "Mickey Mousecapade (USA).nes",
    "Mighty Final Fight (USA).nes",
    "Mike Tyson's Punch-Out (Japan, USA) (En) (Rev 1).nes",
    "Moai-kun (Japan).nes",
    "Ms. Pac-Man (USA) (Tengen) (Unl).nes",
    "Nekketsu Kakutou Densetsu (Japan).nes",
    "Nekketsu Street Basket - Ganbare Dunk Heroes (Japan).nes",
    "Ninja Crusaders (USA).nes",
    "Ninja Gaiden (USA).nes",
    "Ninja Gaiden II - The Dark Sword of Chaos (USA).nes",
    "Ninja Gaiden III - The Ancient Ship of Doom (USA).nes",
    "North and South (USA).nes",
    "Nuts & Milk (Japan).nes",
    "Over Horizon (Japan).nes",
    "Paperboy (USA).nes",
    "Pirates (USA).nes",
    "Popeye (World) (Rev 1).nes",
    "Power Blade (USA).nes",
    "Prince of Persia (USA).nes",
    "Princess Tomato in the Salad Kingdom (USA).nes",
    "Pro Wrestling (USA) (Rev 1).nes",
    "Radia Senki - Reimei Hen (Japan).nes",
    "Rampage (USA).nes",
    "Rampart (USA) (Jaleco).nes",
    "Rescue - The Embassy Mission (USA).nes",
    "River City Ransom (USA).nes",
    "Robin Hood - Prince of Thieves (USA) (Rev 1).nes",
    "Rollergames (USA).nes",
    "Rush'n Attack (USA).nes",
    "Rygar (USA) (Rev 1).nes",
    "S.C.A.T. - Special Cybernetic Attack Team (USA).nes",
    "Shadow of the Ninja (USA).nes",
    "Shadowgate (USA).nes",
    "Shatterhand (USA).nes",
    "Ski or Die (USA).nes",
    "Smash T.V. (USA).nes",
    "smb.nes",
    "Snake Rattle n Roll (USA).nes",
    "Soccer (Japan, USA) (En).nes",
    "Softball Tengoku (Japan).nes",
    "Sonic the Hedgehog (Unl).nes",
    "Spelunker (USA).nes",
    "StarTropics (USA).nes",
    "Street Fighter 2010 - The Final Fight (USA).nes",
    "Street Fighter II (Unl).nes",
    "Strider (USA).nes",
    "Super Contra (Japan).nes",
    "Super Dodge Ball (USA).nes",
    "Super Mario Bros. (World).nes",
    "Super Mario Bros. - Two Player Mod (Unl).nes",
    "Super Mario Bros. 2 (USA) (Rev 1).nes",
    "Super Mario Bros. 3 (USA) (Rev 1).nes",
    "Super Pitfall (USA).nes",
    "Super Spike V'Ball (USA).nes",
    "Tecmo Super Bowl (USA).nes",
    "Tecmo World Wrestling (USA).nes",
    "Teenage Mutant Ninja Turtles - Tournament Fighters (USA).nes",
    "Teenage Mutant Ninja Turtles II - The Arcade Game (USA).nes",
    "Teenage Mutant Ninja Turtles III - The Manhattan Project (USA).nes",
    "Tennis (Japan, USA) (En).nes",
    "Tetris (USA).nes",
    "The Legend of Zelda - Ancient Dungeon (Unl).nes",
    "Tiny Toon Adventures (USA).nes",
    "Track & Field (USA).nes",
    "Trojan (USA).nes",
    "Urban Champion (World).nes",
    "Vice - Project Doom (USA).nes",
    "Wild Gunman (World) (Rev 1).nes",
    "Wizards & Warriors (USA) (Rev 1).nes",
    "Wrecking Crew (World).nes",
    "Yie Ar Kung-Fu (Japan) (Rev 1.4).nes",
    "Zelda II - The Adventure of Link (USA).nes",
    "Zen - Intergalactic Ninja (USA).nes",
]

# Generate HTML code
html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NES Game Downloads</title>
</head>
<body>

    <h1>NES Game Downloads</h1>

    <ul>
"""

for game in nes_games:
    html_code += f"""
        <!-- {game} -->
        <li><a href="/nes/{game.replace(" ", "").replace("(", "").replace(")", "")}.nes" download="{game.replace("(", "").replace(")", "")}.nes"><button class="btn"><i class="fa fa-download"></i>{game}</button></a></li>
        <p></p>
"""

html_code += """
    </ul>

</body>
</html>
"""

# Save HTML code to a file
with open("nes_games.html", "w") as file:
    file.write(html_code)

print("HTML code generated and saved to 'nes_games.html'")
